<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Matthew Kay" />
  <meta name="date" content="2015-12-06" />
  <title>Contrast tests with ART</title>
  <style type="text/css">code{white-space: pre;}</style>
  <style type="text/css">
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; }
code > span.dt { color: #902000; }
code > span.dv { color: #40a070; }
code > span.bn { color: #40a070; }
code > span.fl { color: #40a070; }
code > span.ch { color: #4070a0; }
code > span.st { color: #4070a0; }
code > span.co { color: #60a0b0; font-style: italic; }
code > span.ot { color: #007020; }
code > span.al { color: #ff0000; font-weight: bold; }
code > span.fu { color: #06287e; }
code > span.er { color: #ff0000; font-weight: bold; }
  </style>
  <link rel="stylesheet" href="github-markdown.css" type="text/css" />
</head>
<body>
<div id="header">
<h1 class="title">Contrast tests with ART</h1>
<h2 class="author">Matthew Kay</h2>
<h3 class="date">2015-12-06</h3>
</div>
<p>The aligned-rank transform (ART) allows for non-parametric analyses of variance. But how should we do contrast tests with ART?</p>
<p><strong>Within a single factor</strong>, contrasts in ART are straightforward: simply conduct contrasts on the linear model containing the response aligned for that factor.</p>
<p><strong>For interactions</strong>, which necessarily involve effects across factors, what types of contrasts are valid may not be immediately obvious. This page explains what types of interaction contrasts are appropriate on aligned-rank-transformed (ART) data, what are not, and why.</p>
<h2 id="contents">Contents</h2>
<ol style="list-style-type: decimal">
<li><a href="#test-dataset">Test Dataset</a>: Description of the test data we will use to compare a linear model against ART</li>
<li><a href="#contrast-tests-of-main-effects">Contrast tests of main effects</a>: Demo of conducting contrasts within a single factor (no interaction)</li>
<li><a href="#tests-of-differences-in-pairwise-combinations-of-levels-between-factors-in-interactions">Tests of differences in pairwise combinations of levels between factors in interactions</a>: Interaction contrasts that <strong>are not valid</strong> in ART</li>
<li><a href="#tests-of-differences-of-differences-in-interactions">Tests of differences of differences in interactions</a>: Interaction contrasts that <strong>are valid</strong> in ART</li>
</ol>
<h2 id="libraries-needed-for-this">Libraries needed for this</h2>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ARTool)     <span class="co">#art, artlm</span>
<span class="kw">library</span>(dplyr)      <span class="co">#data_frame, %&gt;%, filter, etc</span>
<span class="kw">library</span>(lsmeans)    <span class="co">#lsmeans</span>
<span class="kw">library</span>(phia)       <span class="co">#testInteractions</span>
<span class="kw">library</span>(tidyr)      <span class="co">#spread, gather</span>
<span class="kw">library</span>(ggplot2)    <span class="co">#ggplot, stat_..., geom_..., etc</span></code></pre>
<h2 id="test-dataset">Test dataset</h2>
<p>Let's generate some test data where we actually know what the effects are. Specifically,</p>
<pre class="sourceCode r"><code class="sourceCode r">n_per_group =<span class="st"> </span><span class="dv">150</span>
df =<span class="st"> </span><span class="kw">data_frame</span>(
    <span class="dt">X1 =</span> <span class="kw">factor</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;A&quot;</span>, n_per_group), <span class="kw">rep</span>(<span class="st">&quot;B&quot;</span>, n_per_group))),
    <span class="dt">X2 =</span> <span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;C&quot;</span>,<span class="st">&quot;D&quot;</span>,<span class="st">&quot;E&quot;</span>), n_per_group*<span class="dv">2</span>/<span class="dv">3</span>)),
    <span class="dt">Y =</span> <span class="kw">rnorm</span>(n_per_group*<span class="dv">2</span>, 
        (X1 ==<span class="st"> &quot;B&quot;</span>)
        +<span class="st"> </span><span class="dv">2</span>*<span class="st"> </span>(X2 ==<span class="st"> &quot;D&quot;</span>)
        +<span class="st"> </span><span class="dv">2</span> *<span class="st"> </span>(X1 ==<span class="st"> &quot;B&quot;</span> &amp;<span class="st"> </span>X2 ==<span class="st"> &quot;D&quot;</span>)
        -<span class="st"> </span><span class="dv">2</span> *<span class="st"> </span>(X1 ==<span class="st"> &quot;A&quot;</span> &amp;<span class="st"> </span>X2 ==<span class="st"> &quot;D&quot;</span>)
        +<span class="st"> </span><span class="dv">2</span> *<span class="st"> </span>(X2 ==<span class="st"> &quot;E&quot;</span>)) 
)</code></pre>
<p>This is normally-distributed error with the same variance at all levels, so we can compare the results of ART to a linear model, which will correctly estimate the effects.</p>
<p>I pre-ran the above code and saved it as <code>InteractionTestData</code> so that the text here is consistent:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;InteractionTestData&quot;</span>)
df =<span class="st"> </span>InteractionTestData    <span class="co">#save some typing</span></code></pre>
<p>The &quot;true&quot; means from the model look like this:</p>
<table>
<thead>
<tr class="header">
<th align="center">X1</th>
<th align="center">X2</th>
<th align="center">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">A</td>
<td align="center">C or D</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">A</td>
<td align="center">E</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">B</td>
<td align="center">C</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">B</td>
<td align="center">D</td>
<td align="center">5</td>
</tr>
<tr class="odd">
<td align="center">B</td>
<td align="center">E</td>
<td align="center">3</td>
</tr>
</tbody>
</table>
<p>Which we can see pretty well:</p>
<pre class="sourceCode r"><code class="sourceCode r">palette =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;#1b9e77&quot;</span>, <span class="st">&quot;#d95f02&quot;</span>, <span class="st">&quot;#7570b3&quot;</span>)
<span class="kw">names</span>(palette) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span>)
<span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x=</span>X1, <span class="dt">y=</span>Y, <span class="dt">color=</span>X2)) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_violin</span>(<span class="dt">trim=</span><span class="ot">FALSE</span>, <span class="dt">adjust=</span><span class="fl">1.5</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">pch=</span><span class="st">&quot;-&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) +
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;point&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>, <span class="dt">size=</span><span class="dv">1</span>, <span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">group=</span>X2)) +
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;point&quot;</span>, <span class="dt">size=</span><span class="dv">9</span>, <span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span><span class="fl">1.5</span>, <span class="dt">group=</span><span class="ot">NA</span>), <span class="dt">pch=</span><span class="st">&quot;+&quot;</span>) +
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(-<span class="dv">6</span>,<span class="dv">10</span>,<span class="dt">by=</span><span class="dv">2</span>), <span class="dt">minor_breaks=</span>-<span class="dv">6</span>:<span class="dv">10</span>) +
<span class="st">    </span><span class="kw">scale_color_manual</span>(<span class="dt">guide=</span><span class="ot">FALSE</span>, <span class="dt">values=</span>palette) +
<span class="st">    </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim=</span><span class="kw">c</span>(-<span class="dv">6</span>,<span class="dv">10</span>)) +<span class="st"> </span>
<span class="st">    </span><span class="kw">facet_grid</span>(. ~<span class="st"> </span>X2)</code></pre>
<div class="figure">
<img src="figure/interaction_plot-1.png" />
</div>
<p>And &quot;true&quot; means for each level (averaging over the levels of the other factor):</p>
<table>
<thead>
<tr class="header">
<th align="center">Level</th>
<th align="center">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">X1 == A</td>
<td align="center">0.66666</td>
</tr>
<tr class="even">
<td align="center">X1 == B</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">X2 == C</td>
<td align="center">0.5</td>
</tr>
<tr class="even">
<td align="center">X2 == D</td>
<td align="center">2.5</td>
</tr>
<tr class="odd">
<td align="center">X2 == E</td>
<td align="center">2.5</td>
</tr>
</tbody>
</table>
<p>Let's fit a linear model:</p>
<pre class="sourceCode r"><code class="sourceCode r">m.linear =<span class="st"> </span><span class="kw">lm</span>(Y ~<span class="st"> </span>X1*X2, <span class="dt">data=</span>df)
<span class="kw">anova</span>(m.linear)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Y
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## X1          1 445.50  445.50  439.44 &lt; 2.2e-16 ***
## X2          2 236.44  118.22  116.61 &lt; 2.2e-16 ***
## X1:X2       2 270.40  135.20  133.36 &lt; 2.2e-16 ***
## Residuals 294 298.06    1.01                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Now with ART:</p>
<pre class="sourceCode r"><code class="sourceCode r">m.art =<span class="st"> </span><span class="kw">art</span>(Y ~<span class="st"> </span>X1*X2, <span class="dt">data=</span>df)
<span class="kw">anova</span>(m.art)</code></pre>
<pre><code>## Analysis of Variance of Aligned Rank Transformed Data
## 
## Table Type: Anova Table (Type III tests) 
## Model: No Repeated Measures (lm)
## Response: art(Y)
## 
##         Df Df.res F value     Pr(&gt;F)    
## 1 X1     1    294  488.33 &lt; 2.22e-16 ***
## 2 X2     2    294  114.35 &lt; 2.22e-16 ***
## 3 X1:X2  2    294  145.65 &lt; 2.22e-16 ***
## ---
## Signif. codes:   0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Both have significance at all levels (expected given the number of samples and the &quot;true&quot; effects) and similar enough F values. The real question is whether/what kind of contrast tests make sense.</p>
<h3 id="contrast-tests-of-main-effects">Contrast tests of main effects</h3>
<p>For the main effects, let's look at contrast tests for the linear model:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lsmeans</span>(m.linear, pairwise ~<span class="st"> </span>X1)$contrasts</code></pre>
<pre><code>##  contrast  estimate        SE  df t.ratio p.value
##  A - B    -2.437216 0.1162643 294 -20.963  &lt;.0001
## 
## Results are averaged over the levels of: X2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lsmeans</span>(m.linear, pairwise ~<span class="st"> </span>X2)$contrasts</code></pre>
<pre><code>##  contrast    estimate        SE  df t.ratio p.value
##  C - D    -1.91212883 0.1423941 294 -13.428  &lt;.0001
##  C - E    -1.85296777 0.1423941 294 -13.013  &lt;.0001
##  D - E     0.05916106 0.1423941 294   0.415  0.9093
## 
## Results are averaged over the levels of: X1 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>These are about right: The &quot;true&quot; effect for <code>A - B</code> is <code>-2.3333</code>, for <code>C - D</code> and <code>C - E</code> is <code>-2</code>, and for <code>D - E</code> is <code>0</code> (see table above). From ART:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lsmeans</span>(<span class="kw">artlm</span>(m.art, <span class="st">&quot;X1&quot;</span>), pairwise ~<span class="st"> </span>X1)$contrasts</code></pre>
<pre><code>##  contrast  estimate       SE  df t.ratio p.value
##  A - B    -136.8133 6.191181 294 -22.098  &lt;.0001
## 
## Results are averaged over the levels of: X2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lsmeans</span>(<span class="kw">artlm</span>(m.art, <span class="st">&quot;X2&quot;</span>), pairwise ~<span class="st"> </span>X2)$contrasts</code></pre>
<pre><code>##  contrast estimate       SE  df t.ratio p.value
##  C - D     -123.13 9.277428 294 -13.272  &lt;.0001
##  C - E     -119.81 9.277428 294 -12.914  &lt;.0001
##  D - E        3.32 9.277428 294   0.358  0.9319
## 
## Results are averaged over the levels of: X1 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>This is about right (effects in the same direction, the estimates aren't the same because they are on the scale of ranks and not the data, but the t values are similar to the linear model, as we should hope). Contrast tests of main effects seem to be consistent then.</p>
<h3 id="tests-of-differences-in-pairwise-combinations-of-levels-between-factors-in-interactions">Tests of differences in pairwise combinations of levels between factors in interactions</h3>
<p>Now let's look at tests of differences in combinations of levels between factors:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lsmeans</span>(m.linear, pairwise ~<span class="st"> </span>X1:X2)$contrasts</code></pre>
<pre><code>##  contrast       estimate        SE  df t.ratio p.value
##  A,C - B,C -1.2901606831 0.2013757 294  -6.407  &lt;.0001
##  A,C - A,D -0.0005062796 0.2013757 294  -0.003  1.0000
##  A,C - B,D -5.1139120652 0.2013757 294 -25.395  &lt;.0001
##  A,C - A,E -2.0440071593 0.2013757 294 -10.150  &lt;.0001
##  A,C - B,E -2.9520890651 0.2013757 294 -14.660  &lt;.0001
##  B,C - A,D  1.2896544035 0.2013757 294   6.404  &lt;.0001
##  B,C - B,D -3.8237513821 0.2013757 294 -18.988  &lt;.0001
##  B,C - A,E -0.7538464761 0.2013757 294  -3.743  0.0030
##  B,C - B,E -1.6619283819 0.2013757 294  -8.253  &lt;.0001
##  A,D - B,D -5.1134057856 0.2013757 294 -25.392  &lt;.0001
##  A,D - A,E -2.0435008796 0.2013757 294 -10.148  &lt;.0001
##  A,D - B,E -2.9515827854 0.2013757 294 -14.657  &lt;.0001
##  B,D - A,E  3.0699049060 0.2013757 294  15.245  &lt;.0001
##  B,D - B,E  2.1618230002 0.2013757 294  10.735  &lt;.0001
##  A,E - B,E -0.9080819058 0.2013757 294  -4.509  0.0001
## 
## P value adjustment: tukey method for comparing a family of 6 estimates</code></pre>
<p>And for ART:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#DO NOT DO THIS!</span>
<span class="kw">lsmeans</span>(<span class="kw">artlm</span>(m.art, <span class="st">&quot;X1:X2&quot;</span>), pairwise ~<span class="st"> </span>X1:X2)$contrasts</code></pre>
<pre><code>##  contrast  estimate       SE  df t.ratio p.value
##  A,C - B,C    76.90 12.39868 294   6.202  &lt;.0001
##  A,C - A,D   125.12 12.39868 294  10.091  &lt;.0001
##  A,C - B,D   -45.26 12.39868 294  -3.650  0.0042
##  A,C - A,E   -12.08 12.39868 294  -0.974  0.9258
##  A,C - B,E    87.16 12.39868 294   7.030  &lt;.0001
##  B,C - A,D    48.22 12.39868 294   3.889  0.0017
##  B,C - B,D  -122.16 12.39868 294  -9.853  &lt;.0001
##  B,C - A,E   -88.98 12.39868 294  -7.177  &lt;.0001
##  B,C - B,E    10.26 12.39868 294   0.828  0.9623
##  A,D - B,D  -170.38 12.39868 294 -13.742  &lt;.0001
##  A,D - A,E  -137.20 12.39868 294 -11.066  &lt;.0001
##  A,D - B,E   -37.96 12.39868 294  -3.062  0.0288
##  B,D - A,E    33.18 12.39868 294   2.676  0.0832
##  B,D - B,E   132.42 12.39868 294  10.680  &lt;.0001
##  A,E - B,E    99.24 12.39868 294   8.004  &lt;.0001
## 
## P value adjustment: tukey method for comparing a family of 6 estimates</code></pre>
<p>Very different results.</p>
<p>The linear model tests are easy to interpret: they tell us the expected mean difference between combinations of levels.</p>
<p>The ART results are more difficult to interpret. Take <code>A,C - A,D</code>, which looks like this:</p>
<pre class="sourceCode r"><code class="sourceCode r">df %&gt;%
<span class="st">    </span><span class="kw">filter</span>(X1 ==<span class="st"> &quot;A&quot;</span>, X2 %in%<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>)) %&gt;%
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>X1:X2, <span class="dt">y=</span>Y, <span class="dt">color=</span>X2)) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_violin</span>(<span class="dt">trim=</span><span class="ot">FALSE</span>, <span class="dt">adjust=</span><span class="fl">1.5</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">pch=</span><span class="st">&quot;-&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) +
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;point&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(-<span class="dv">6</span>,<span class="dv">10</span>,<span class="dt">by=</span><span class="dv">2</span>), <span class="dt">minor_breaks=</span>-<span class="dv">6</span>:<span class="dv">10</span>) +
<span class="st">    </span><span class="kw">scale_color_manual</span>(<span class="dt">guide=</span><span class="ot">FALSE</span>, <span class="dt">values=</span>palette) +
<span class="st">    </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim=</span><span class="kw">c</span>(-<span class="dv">6</span>,<span class="dv">10</span>)) </code></pre>
<div class="figure">
<img src="figure/interaction_plot_AC_AD-1.png" />
</div>
<p>The linear model correctly estimates this difference as <code>~0</code>, which is both the true effect and what we should expect from a visual inspection of the data. Unlike the linear model, the ART model gives us a statistically significant difference between <code>A,C</code> and <code>A,D</code>, which if we interpret in the same way as the linear model is obviously incorrect.</p>
<p>The key here is to understand that ART is reporting differences with the main effects subtracted out. That is, the <code>A,C - A,D</code> effect is something like the difference between this combination of levels if we first subtracted out the effect of <code>C - D</code>. We can see this if we take the ART estimate for <code>C - D</code> in the lsmeans for <code>X2</code> above (<code>-123.13</code>) and the ART estimate for <code>A,C - A,D</code> (<code>125.12</code>) here, we can get approximate an estimate of the difference (<code>-123.13 + 125.12 == 1.99</code>) that is consistent with the expected 0 (given the SE here).</p>
<p>If we first combine the factors before aligning-and-ranking, we can get an estimate of these effects:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#DO NOT DO THIS WITHOUT READING THE NOTE BELOW</span>
df$X =<span class="st"> </span><span class="kw">with</span>(df, X1:X2)
m.art<span class="fl">.12</span> =<span class="st"> </span><span class="kw">art</span>(Y ~<span class="st"> </span>X, <span class="dt">data=</span>df)
<span class="kw">lsmeans</span>(<span class="kw">artlm</span>(m.art<span class="fl">.12</span>, <span class="st">&quot;X&quot;</span>), pairwise ~<span class="st"> </span>X)$contrasts</code></pre>
<pre><code>##  contrast  estimate       SE  df t.ratio p.value
##  A:C - A:D     1.96 8.908834 294   0.220  0.9999
##  A:C - A:E  -100.96 8.908834 294 -11.333  &lt;.0001
##  A:C - B:C   -63.16 8.908834 294  -7.090  &lt;.0001
##  A:C - B:D  -205.76 8.908834 294 -23.096  &lt;.0001
##  A:C - B:E  -141.84 8.908834 294 -15.921  &lt;.0001
##  A:D - A:E  -102.92 8.908834 294 -11.553  &lt;.0001
##  A:D - B:C   -65.12 8.908834 294  -7.310  &lt;.0001
##  A:D - B:D  -207.72 8.908834 294 -23.316  &lt;.0001
##  A:D - B:E  -143.80 8.908834 294 -16.141  &lt;.0001
##  A:E - B:C    37.80 8.908834 294   4.243  0.0004
##  A:E - B:D  -104.80 8.908834 294 -11.764  &lt;.0001
##  A:E - B:E   -40.88 8.908834 294  -4.589  0.0001
##  B:C - B:D  -142.60 8.908834 294 -16.007  &lt;.0001
##  B:C - B:E   -78.68 8.908834 294  -8.832  &lt;.0001
##  B:D - B:E    63.92 8.908834 294   7.175  &lt;.0001
## 
## P value adjustment: tukey method for comparing a family of 6 estimates</code></pre>
<p>Note that the above table is not in the same order as the previous ones, but does have similar t values to the corresponding effects from the linear model. <strong>However, it is not clear this will generalize.</strong> In this case there aren't any other factors except these two, so this is equivalent to just ranking the response before fitting the model, and in the general case it can incorrectly estimate interactions (see issues with using the plain-old rank transform in the ART literature, specifically Higgins' papers). Thus, I can't recommended this approach in the general case (or at least, not without more investigation).</p>
<h3 id="tests-of-differences-of-differences-in-interactions">Tests of <em>differences of differences</em> in interactions</h3>
<p>While tests of differences of combinations of levels between factors have issues in ART, we can test <em>differences of differences</em>; e.g., for the interaction <code>X1:X2</code>, we might ask, is the difference <code>A - B</code> different when <code>X2 = C</code> compared to when <code>X2 = D</code>? We can test this using the <code>testInteractions</code> function from package <code>phia</code>.</p>
<p>Before we test, let's try to visualize what's going on in just this interaction:</p>
<pre class="sourceCode r"><code class="sourceCode r">plot_interaction_for_X2_levels =<span class="st"> </span>function(...) {
    x2_levels =<span class="st"> </span><span class="kw">c</span>(...)
    df. =<span class="st"> </span><span class="kw">filter</span>(df, X2 %in%<span class="st"> </span>x2_levels)
    X1_in_X2 =<span class="st"> </span>df. %&gt;%
<span class="st">        </span><span class="kw">group_by</span>(X1, X2) %&gt;%
<span class="st">        </span><span class="kw">summarise</span>(<span class="dt">Y =</span> <span class="kw">mean</span>(Y)) %&gt;%
<span class="st">        </span><span class="kw">spread</span>(X1, Y)
    <span class="kw">print</span>(<span class="kw">ggplot</span>(df., <span class="kw">aes</span>(<span class="dt">x=</span>X1, <span class="dt">y=</span>Y, <span class="dt">color=</span>X2)) +<span class="st">  </span>
<span class="st">        </span><span class="kw">geom_violin</span>(<span class="dt">trim=</span><span class="ot">FALSE</span>, <span class="dt">adjust=</span><span class="fl">1.5</span>) +<span class="st"> </span>
<span class="st">        </span><span class="kw">geom_point</span>(<span class="dt">pch=</span><span class="st">&quot;-&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) +
<span class="st">        </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;point&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) +<span class="st"> </span>
<span class="st">        </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>, <span class="dt">size=</span><span class="dv">1</span>, <span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">group=</span>X2), <span class="dt">linetype=</span><span class="st">&quot;dashed&quot;</span>) +
<span class="st">        </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">x=</span><span class="fl">2.2</span>, <span class="dt">ymin=</span>A, <span class="dt">ymax=</span>B, <span class="dt">y=</span><span class="dv">0</span>), 
            <span class="dt">data=</span>X1_in_X2, <span class="dt">width=</span>.<span class="dv">19</span>, <span class="dt">size=</span><span class="fl">0.8</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>) +
<span class="st">        </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">x=</span><span class="fl">2.35</span>, <span class="dt">y=</span>(A +<span class="st"> </span>B)/<span class="dv">2</span>, <span class="dt">label=</span><span class="kw">paste</span>(<span class="st">&quot;A - B |&quot;</span>, X2)), 
            <span class="dt">data=</span>X1_in_X2, <span class="dt">hjust=</span><span class="dv">0</span>, <span class="dt">size=</span><span class="dv">5</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>) +
<span class="st">        </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(-<span class="dv">6</span>,<span class="dv">10</span>,<span class="dt">by=</span><span class="dv">2</span>), <span class="dt">minor_breaks=</span>-<span class="dv">6</span>:<span class="dv">10</span>) +
<span class="st">        </span><span class="kw">scale_color_manual</span>(<span class="dt">guide=</span><span class="ot">FALSE</span>, <span class="dt">values=</span>palette[x2_levels]) +<span class="st"> </span>
<span class="st">        </span><span class="kw">coord_cartesian</span>(<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">3.5</span>), <span class="dt">ylim=</span><span class="kw">c</span>(-<span class="dv">6</span>,<span class="dv">10</span>)) +
<span class="st">        </span><span class="kw">facet_grid</span>(. ~<span class="st"> </span>X2))
}
<span class="kw">plot_interaction_for_X2_levels</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/interaction_plot_C_D-1.png" />
</div>
<p>The true effect for <code>A - B | C</code> is -1, for <code>A - B | D</code> is -5, and for <code>(A - B | C) - (A - B | D)</code> is <code>(-1) - (-5) = 4</code>. Visually, we're asking if the two dashed lines in the above plot are parallel. Equivalently, we're asking if the vertical distance from the mean of A to the mean of B in the left panel (when X2 == C) is the same as the vertical distance between A and B in the right panel (when X2 == D). The true difference between these vertical distances (the &quot;difference of a difference&quot;) is 4, which is also about what we would estimate it to be by looking at the above plot.</p>
<p>We can get the estimate of this &quot;difference of a difference&quot; from the linear model:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#unfortunately, the meaning of &quot;pairwise&quot; here isn&#39;t the same as how lsmeans</span>
<span class="co">#uses it when multiple factors are involved --- here we get differences of differences.</span>
<span class="kw">testInteractions</span>(m.linear, <span class="dt">pairwise=</span><span class="kw">c</span>(<span class="st">&quot;X1&quot;</span>, <span class="st">&quot;X2&quot;</span>))</code></pre>
<pre><code>## F Test: 
## P-value adjustment method: holm
##             Value  Df Sum of Sq      F Pr(&gt;F)    
## A-B : C-D  3.8232   1   182.715 180.23 &lt;2e-16 ***
## A-B : C-E -0.3821   1     1.825   1.80 0.1808    
## A-B : D-E -4.2053   1   221.059 218.05 &lt;2e-16 ***
## Residuals         294   298.059                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here we can interpret the row <code>A-B : C-D</code> as the difference between (<code>A-B | C</code>) and (<code>A-B | D</code>), which is estimated as <code>3.82</code> (close to the true effect of 4, see the plot above).</p>
<p>We can look at a similar plot for <code>A-B : C-E</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot_interaction_for_X2_levels</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;E&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/interaction_plot_C_E-1.png" />
</div>
<p>Here the true effect for <code>A - B | C</code> is -1, <code>A - B | E</code> is also -1, and <code>(A - B | C) - (A - B | E)</code> is <code>0</code>. Visually, this sample looks close to the true effects (the height of <code>A - B | C</code> is about the same as <code>A - B | E</code>). From the the row <code>A-B : C-E</code> above we can see that the estimate from the linear model is ~0, as we should hope.</p>
<p>A similar visual analysis finds the estimate for <code>A-B : D-E</code> (~ -4.2) also to be correct (true effect is -4):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot_interaction_for_X2_levels</span>(<span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/interaction_plot_D_E-1.png" />
</div>
<p>Now we look at these differences of differences in art:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">testInteractions</span>(<span class="kw">artlm</span>(m.art, <span class="st">&quot;X1:X2&quot;</span>), <span class="dt">pairwise=</span><span class="kw">c</span>(<span class="st">&quot;X1&quot;</span>, <span class="st">&quot;X2&quot;</span>))</code></pre>
<pre><code>## F Test: 
## P-value adjustment method: holm
##             Value  Df Sum of Sq        F Pr(&gt;F)    
## A-B : C-D  247.28   1    764342 198.8827 &lt;2e-16 ***
## A-B : C-E  -22.34   1      6238   1.6232 0.2036    
## A-B : D-E -269.62   1    908687 236.4412 &lt;2e-16 ***
## Residuals         294   1129896                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And we see F values consistent with the linear model and the same effect directions. These types of comparisons work under ART because they do not involve coefficients of main effects (see the description of these tests in <a href="https://cran.r-project.org/web/packages/phia/vignettes/phia.pdf">this phia vignette</a>), thus are consistent even when we've stripped out the main effects.</p>
</body>
</html>
